--Lab 8
--Perform SQL queries for Group by with having and Order by

CREATE TABLE SALES_DATA(
	REGION VARCHAR(15),
	PRODUCT VARCHAR(10),
	SALES_AMOUNT DECIMAL(8,2),
	YEAR_ VARCHAR(6)
);

SELECT * FROM SALES_DATA;

INSERT INTO SALES_DATA VALUES('NORTH AMERICA' , 'WATCH' , 1500 , '2023');
INSERT INTO SALES_DATA VALUES('EUROPE' , 'MOBILE' , 1200 , '2023');
INSERT INTO SALES_DATA VALUES('ASIA' , 'WATCH' , 1800 , '2023');
INSERT INTO SALES_DATA VALUES('NORTH AMERICA' , 'TV' , 900 , '2024');
INSERT INTO SALES_DATA VALUES('EUROPE' , 'WATCH' , 2000 , '2024');
INSERT INTO SALES_DATA VALUES('ASIA' , 'MOBILE' , 1000 , '2024');
INSERT INTO SALES_DATA VALUES('NORTH AMERICA' , 'MOBILE' , 1600 , '2023');
INSERT INTO SALES_DATA VALUES('EUROPE' , 'TV' , 1500 , '2023');
INSERT INTO SALES_DATA VALUES('ASIA' , 'TV' , 1100 , '2024');
INSERT INTO SALES_DATA VALUES('NORTH AMERICA' , 'WATCH' , 1700 , '2024');

--Part – A:


--1.Display Total Sales Amount by Region.
SELECT SUM(SALES_AMOUNT) AS TOTAL_SALES_AMOUNT_BY_REGION FROM SALES_DATA GROUP BY REGION;

--2.Display Average Sales Amount by Product
SELECT AVG(SALES_AMOUNT) AS AVERAGE_SALES_AMOUNT_BY_PRODUCT FROM SALES_DATA GROUP BY PRODUCT;
 
--3.Display Maximum Sales Amount by Year
SELECT MAX(SALES_AMOUNT) AS MAXIMUN_SALES_AMOUNT_BY_YEAR FROM SALES_DATA GROUP BY YEAR_;

--4.Display Minimum Sales Amount by Region and Year
SELECT MIN(SALES_AMOUNT) AS MINIMUM_SALES_AMOUNT_BY_YEAR_BY_REGION FROM SALES_DATA GROUP BY YEAR_ , REGION;

--5.Count of Products Sold by Region
SELECT COUNT(PRODUCT) AS COUNT_OF_PRODUCT_SOLD_BY_REGION FROM SALES_DATA GROUP BY REGION;

--6.Display Sales Amount by Year and Product
SELECT SUM(SALES_AMOUNT) AS SALES_AMOUNT_BY_YEAR_AND_PRODUCT FROM SALES_DATA GROUP BY YEAR_ , PRODUCT;

--7.Display Regions with Total Sales Greater Than 5000
SELECT REGION , SUM(SALES_AMOUNT) FROM SALES_DATA GROUP BY REGION HAVING SUM(SALES_AMOUNT)>5000;

--8.Display Products with Average Sales Less Than 10000
SELECT PRODUCT , AVG(SALES_AMOUNT) FROM SALES_DATA GROUP BY PRODUCT HAVING AVG(SALES_AMOUNT)<10000;

--9.Display Years with Maximum Sales Exceeding 500
SELECT YEAR_ , MAX(SALES_AMOUNT) FROM SALES_DATA GROUP BY YEAR_ HAVING MAX(SALES_AMOUNT)>500;

--10.Display Regions with at Least 3 Distinct Products Sold.
SELECT DISTINCT PRODUCT , COUNT(PRODUCT) FROM SALES_DATA GROUP BY PRODUCT HAVING COUNT(PRODUCT)>3;

--11.Display Years with Minimum Sales Less Than 1000
SELECT YEAR_ , COUNT(YEAR_) FROM SALES_DATA GROUP BY YEAR_ HAVING MIN(SALES_AMOUNT)>1000;

--12.Display Total Sales Amount by Region for Year 2023, Sorted by Total Amount
SELECT SUM(SALES_AMOUNT) AS TOTAL_AMOUNT_BY_REGION  FROM SALES_DATA  WHERE YEAR_ = '2023' GROUP BY REGION ORDER BY SUM(SALES_AMOUNT);  

--Part – B:

--1.Display Count of Orders by Year and Region, Sorted by Year and Region
SELECT COUNT(YEAR_) AS COUNT_OF_YEAR , COUNT(REGION) AS COUNT_OF_REGION FROM SALES_DATA ORDER BY COUNT(YEAR_) , COUNT(REGION);

--2.Display Regions with Maximum Sales Amount Exceeding 1000 in Any Year, Sorted by Region
SELECT REGION , MAX(SALES_AMOUNT) FROM SALES_DATA GROUP BY REGION HAVING MAX(SALES_AMOUNT) > 1000 ORDER BY REGION;

--3.Display Years with Total Sales Amount Less Than 1000, Sorted by Year Descending
SELECT YEAR_ , SUM(SALES_AMOUNT) FROM SALES_DATA GROUP BY YEAR_ HAVING SUM(SALES_AMOUNT) < 1000 ORDER BY YEAR_ DESC;

--4.Display Top 3 Regions by Total Sales Amount in Year 2024
SELECT TOP 3 REGION , SUM(SALES_AMOUNT) FROM SALES_DATA WHERE YEAR_ = '2024' GROUP BY SALES_AMOUNT , REGION ;

--Part – C:

--1.Display Products with Average Sales Amount Between 1000 and 2000, Ordered by Product Name
SELECT PRODUCT , AVG(SALES_AMOUNT) AS AVRAGE_SALES_AMOUNT FROM SALES_DATA WHERE SALES_AMOUNT BETWEEN 1000 AND 2000 GROUP BY PRODUCT ORDER BY PRODUCT;

--2.Display Years with More Than 5 Orders from Each Region
SELECT REGION , YEAR_  FROM SALES_DATA GROUP BY YEAR_ , REGION HAVING COUNT(YEAR_) > 5;

--3.Display Regions with Average Sales Amount Above 1500 in Year 2023 sort by amount in descending.
SELECT REGION , AVG(SALES_AMOUNT) AS AVERAGE_SALES_AMOUNT FROM SALES_DATA WHERE YEAR_ = '2023' GROUP BY REGION , SALES_AMOUNT HAVING AVG(SALES_AMOUNT) > 1500 ORDER BY SALES_AMOUNT DESC; 

--4.Find out region wise duplicate product.
SELECT PRODUCT , REGION , COUNT(PRODUCT) AS DUPLICATE_PR FROM SALES_DATA GROUP BY REGION ,PRODUCT HAVING COUNT(PRODUCT) > 1 ;

--5.Find out region wise highest sales amount.
SELECT REGION , MAX(SALES_AMOUNT) AS MAXIMUM_SALES_AMOUNT FROM SALES_DATA GROUP BY REGION;